### ISSUE TITLE
re.error: missing : at position 31

### ISSUE THREAD

**Issue by ArIjIT8372** [dwisiswant0/apkleaks#48] opened 2021-06-13 03:47 UTC
i am running my kali linux on wsl i am getting this type of error

└─# apkleaks -f ../com.example.client.apk
     _    ____  _  ___               _
    / \  |  _ \| |/ / |    ___  __ _| | _____
   / _ \ | |_) | ' /| |   / _ \/ _` | |/ / __|
  / ___ \|  __/| . \| |__|  __/ (_| |   <\__ \
 /_/   \_\_|   |_|\_\_____\___|\__,_|_|\_\___/
 v2.5.0
 --
 Scanning APK file for URIs, endpoints & secrets
 (c) 2020-2021, dwisiswant0

Can't find jadx binary.
Do you want to download jadx? (Y/n) y

** Downloading jadx...

** Decompiling APK...
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 17

** Scanning against 'com.example.client'

** Done with nothing. ¯\_(ツ)_/¯
Traceback (most recent call last):
  File "/usr/local/bin/apkleaks", line 33, in <module>
    sys.exit(load_entry_point('apkleaks==2.5.0', 'console_scripts', 'apkleaks')())
  File "/usr/local/lib/python3.9/dist-packages/apkleaks-2.5.0-py3.9.egg/apkleaks/cli.py", line 36, in main
    init.scanning()
  File "/usr/local/lib/python3.9/dist-packages/apkleaks-2.5.0-py3.9.egg/apkleaks/apkleaks.py", line 132, in scanning
    thread = threading.Thread(target = self.extract, args = (name, util.finder(pattern, self.tempdir)))
  File "/usr/local/lib/python3.9/dist-packages/apkleaks-2.5.0-py3.9.egg/apkleaks/utils.py", line 18, in finder
    matcher = re.compile(pattern)
  File "/usr/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 805, in _parse
    flags = _parse_flags(source, state, char)
  File "/usr/lib/python3.9/sre_parse.py", line 913, in _parse_flags
    raise source.error(msg, len(char))
re.error: missing : at position 31

**Comment by Aksh095** [comment] 2021-06-16 04:09
same error getting

**Comment by dwisiswant0** [comment] 2021-06-16 06:16
Hi, @ArIjIT8372 & @Aksh095. It should have been fixed in `v2.5.1`. See the root cause [here](https://github.com/dwisiswant0/apkleaks/releases/tag/v2.5.1). Thank y'all!

**Closed by dwisiswant0** 2021-06-16 06:16 UTC
